# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "IITG MUN 2018"
email: "devfest@gdg.org.ua"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
# speakers = contact us
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "About Us"}
 - {permalink: "/contact-us/", text: "Contact Us"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply now"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply now"}

# CHANGE , TODO
apply-link: "/zeppelin/apply/"

# Councils links
lok-sabha-link: "/lok-sabha/"
ecosoc-link: "/ecosoc/"
unga-link: "/unga/"

# Hero Block
heroImage: "hero.png"
heroTitle: "IIT GUWAHATI MUN <typeout>"
eventDate: "SPRING EDITION'18"
typeoutFallback: ""
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply now"}

# About Block
aboutTitle: "LETTER FROM THE SECRETARY GENERAL"
letterContent: "Dear Delegates,\n

As the Secretary General of IIT Guwahati Model United Nations Conference (IITGMUN) 2018, I could not be more venerated to welcome you all on behalf of my passionate team to the most ambitious version of the IIT Guwahati Model United Nations Conference - Alcheringa yet.

Every year, IITGMUN endeavors to provide a simulated learning platform to like-minded folks with a zealous passion for debating, international diplomacy as well as politics, and deliberative problem-solving. As a learning conference, we prioritize the development of mindset for finding the solutions to pressing world issues by putting oneself in the shoes of a country's representative. We believe that the best way to learn about international diplomacy is by actually doing it. At its core, the IITGMUN Conference is planned, organized, and directed in its totality by a passionate team of IIT Guwahati students that hail from different academic and cultural backgrounds, bringing their unique experiences to the dais. Over the years, we have been successful in delivering thought-intensive conferences to novice as well as seasoned delegates.  

The contemporary world scenario has been dominated by disruptions, both positive and negative. While the former can serve as a driving force for the global growth engine, dealing with the latter requires meticulous planning and deliberation. As a proponent of this thought, we have handpicked three agendae for this winter and set the floor for discussion on the same.

Namely:
UNGA: Preparing for Trans-Arctic Seafaring: Resolving the Impasse over the North-West Passage

ECOSOC: Fulfilling UN Sustainable Development Goals in the Age of Artificial Intelligence

Lok Sabha : Elucidation of Privacy and its Consequences as a Right

All these agendae are the product of incessant discussions and brainstorming among the team members to deliver the most debatable and relevant global quandaries to the participants. The selectivity of these agendae itself reflects our commitment to deliver the best we possibly can and traverse beyond the conventional line of thought.
  
We as a generation have the best time and resources, enumerated with the experience of older generations, to shape the world in a way we want. The onus is on us to act and deliberate as the choices of today will be governing the future in an unprecedented manner. 

With an abyssal optimism, I leave you with the mantle and ask you to take part in an event that awaits a brilliant ensemble of delegates who dare to take on upcoming challenges in the world with courage and diplomacy. Wishing you all the very best of luck for the conference.

Sincerely,
Paridhi Kothari
Secretary General
IIT Guwahati Model UN Conference
"
letterImage: "conference.jpg"
aboutBlock:
 - {title: "", image: "conference.jpg", text: "Dear participants, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "450", specialCharacter: "+", info: "Delegates", detail: "from all over India"}
 - {count: "25", specialCharacter: "+", info: "Executive Board", detail: "overall"}
 - {count: "20", specialCharacter: "+", info: "International Press", detail: "from country and beyond"}

# Latest News Block
latestNewsTitle: "COUNCILS"
latestNewsBlock:
 - {title: "Lok Sabha", image: "unsc_logo.jpg", text: "", link: "lok-sabha"}
 - {title: "UNGA", image: "unhrc_logo.png", text: "", link: "unga"}
 - {title: "ECOSOC", image: "ecosoc_logo.jpg", text: "", link: "ecosoc"}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Executive Board"
rockstarSpeakersButtonText: "See all members"

# Reviews Block
reviewsTitle: "Reviews"
reviewsContent: "“Yes, the IITG MUN has amazing discussions, but the best part of this MUN has to be the people. We are united by the strongest bond of common interests. Continuous open dialogue with people we only know by country names during the conference and the supportive MUN community is, by far, its most beautiful part.”- Ariktha Srinivasthan"
reviewsImage: "reviews.jpg"
reviewsBackgroundImage: "reviewsBG.jpg"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Indian Institute of Technology"
venueFeatures: ["Guwahati", "Conference Hall", "Located next to Auditorium"]

# Tweets Feed Block
tweetsFeedTitle: "\"That the powerful play goes on, and you may contribute a verse. What will be your verse?\""
twitterHashTag: "IITGMUN18"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"


# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}


# Team Block
teamBlockTitle: "About us"
aboutUs: "The MUN, or the Model United Nations, is a simulation of the actual UN. The participants pretend to represent a nation, and come to together to discuss the very same issues being debated upon in the UN. This gives a normal person the opportunity to know what’s its like to stand for something more than himself/herself, and to experience the complicated the verbal dance and that politicians and delegates take part in everyday. The MUN is a conclave for ideation by the fresh minds of our nation, to brainstorm solutions to problems plaguing our world. Participants work through the tenuous relationships between nations as they deliberate towards a resolution – and they get to look
nice in a suit and tie while they do it!"

# Contact Us block
contactUsBlockTitle: "Contact Us"
contactUsTopImage: "top-section.jpg"
contacts:
 - {name: "Sujal Harsh Ranjan", designation: "USG Infrastructure", contactNumber: "+91 8486772158", fbLink: "https://www.facebook.com/Suji131211"}
 - {name: "Sangam Sharma", designation: "USG Delegate Affairs", contactNumber: "+91 8486808779", fbLink: "https://www.facebook.com/sangam.sharma.90226628"}
 - {name: "Vijayant Balhara", designation: "USG Social and Economic Affairs", contactNumber: "+91 9811040041", fbLink: "https://www.facebook.com/vijayant.balhara.3"}
locationImage: "location.jpg"

#Sponsors block
sponsorsTitle: "In Association with "
sponsorsList:
 - {title: "mun_planet", image: "mun_planet_logo.png"}
 - {title: "mun_turkey", image: "mun_turkey_logo.png"}

sponsors2Title: "In Collaboration with "
sponsors2List:
 - {title: "techfest_world_mun", image: "techfest_world_mun_logo.png"}
 - {title: "patna_mun", image: "patna_mun_logo.png"}
 

# Apply Block
applyTypes:
 - {type: "Delegate", applyLink: "vedantc98.github.io/zeppelin/coming-soon/", image: "arbit1.jpg"}
 - {type: "Executive Board", applyLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", image: "arbit2.jpg"}
 - {type: "International Press", applyLink: "vedantc98.github.io/zeppelin/coming-soon/", image: "arbit3.jpg"}

lok-sabha-title: "Lok Sabha"
lok-sabha-agenda-text: "A recent landmark verdict by the Hon’ble Supreme Court established Right to Privacy as a Fundamental Right. Supreme Court, in its decision, stated that Right to Privacy is..."
about-lok-sabha-text: "Lok Sabha is composed of representatives of the people chosen by direct election on the basis of the adult suffrage..."
lok-sabha-popup-text-about: "Lok Sabha is composed of representatives of the people chosen by direct election on the basis of the adult suffrage. The maximum strength of the House envisaged by the Constitution is 552, which is made up by election of upto 530 members to represent the States, upto 20 members to represent the Union Territories and not more than two members of the Anglo-Indian Community to be nominated by the Hon'ble President, if,  in his/her opinion, that community is not adequately represented in the House. The total elective membership is distributed among the States in such a way that the ratio between the number of seats allotted to each State and the population of the State is, so far as practicable, the same for all States."
lok-sabha-popup-text-agenda: "A recent landmark verdict by the Hon’ble Supreme Court established Right to Privacy as a Fundamental Right. Supreme Court, in its decision, stated that Right to Privacy is guaranteed to all the citizens of the country by virtue of it being enshrined in the sacred words of the constitution. However, the implications of this revolutionizing decision stand in a stark contrast with some currently enacted laws, the most significant of them being Aadhar’s legal status, Homosexuality and Abortion Laws. Furthermore, the Hon’ble Supreme Court has not presented a rigid legal definition of Right to Privacy, which makes its execution as a Right even more strenuous. A comprehensive and intensive deliberation on the definition of Privacy and its consequences as a Right is crucially needed, because this momentous decision can only reach its full extent when we carve the way to its effective implementation"
lokSabhaTopImage: "lok-sabha-top.jpg"

unga-title: "The United Nations General Assembly"
unga-agenda-text: "One of the greatest consequences of receding Arctic Ice will be the opening up of the Arctic Ocean to worldwide shipping - a transformation comparable to..."
about-unga-text: "The General Assembly (GA) is the main deliberative, policymaking and representative organ of the UN. Decisions on important questions, such as..."
unga-popup-text-about: "The General Assembly (GA) is the main deliberative, policymaking and representative organ of the UN. Decisions on important questions, such as those on peace and security, admission of new members and budgetary matters, require a two-thirds majority. Decisions on other questions are by simple majority. Each of the 193 member states of the United Nations has equal representation. The Assembly has adopted its own rules of procedure and elects its President for each session."
unga-popup-text-agenda: "One of the greatest consequences of receding Arctic Ice will be the opening up of the Arctic Ocean to worldwide shipping - a transformation comparable to what the Panama and Suez Canals brought about. Developing international cooperation is crucial for the just and safe use of this opportunity, preventing it from turning into a massive ecological and economic disaster. The committee shall aim to formulate the trajectory of human cooperation in the Arctic, with regards to shipping in particular. Focused on the deadlock encompassing the Northwest Passage, an expansive plethora of debates shall erupt - from the unprecedented effect on international agreements elsewhere to the environmental paradox pertaining to the use of the passage as a maritime route; a seemingly simple discourse shall perhaps become one the most important negotiations we need to have as a society."
ungaTopImage: "unga-top.jpg"

ecosoc-title: "The Economic and Social Council"
ecosoc-agenda-text: "The major breakthroughs in Artificial Intelligence has led to even smarter machines and devices, capable of performing manual tasks with..."
about-ecosoc-text: "ECOSOC (United Nations Economic and Social Council), one of the six main organs of the United Nations established by the UN Charter..."
ecosoc-popup-text-about: "ECOSOC (United Nations Economic and Social Council), one of the six main organs of the United Nations established by the UN Charter. ECOSOC’s power to initiate policy making is limited to only making recommendations for the General Assembly, still it is the UN’s largest and most complex subsidiary body, In which Decisions are taken by simple majority vote. The committee encourages universal respect for human rights and fundamental freedoms as well as oversees the implementation of the internationally agreed development goals. ECOSOC’s work is performed in functional charge on topics such as human rights, population, social development, statistics, and science and technology. Consists of 54 member states which are elected by the UNGA for running three-year terms, with terms ending on 31 December of the third year."
ecosoc-popup-text-agenda: "The major breakthroughs in Artificial Intelligence has led to even smarter machines and devices, capable of performing manual tasks with splendid accuracy. The field has not experienced any descent and is envisioning even greater capabilities, inching closer to the level of human cognition. But the question that has struck a cord is - what is the future of the big world community, comprising of differences in skills and access to technology, in the time when machine intelligence will be causing big disruptions in almost every sphere of life. What is the way forward for the international community to attain the ambitious UN 2030 Sustainable Development Goals? There will never be a more fruitful time to decide a prosperous and safer future for everyone. With deliberations and policy framework, we can ensure the use of AI for humane and more useful purposes."
ecosocTopImage: "ecosoc-top.jpg"

locationLink: "https://www.google.co.in/maps/place/IIT+Guwahati+Conference+Hall/@26.1920316,91.6878585,17z/data=!4m5!3m4!1s0x375a5ac17d2b58d7:0xb853cd7b55039193!8m2!3d26.191117!4d91.692547?hl=en"
teamImage: "team.jpg"
signatureImage: "signature.png"